# Generated by Django 5.1.6 on 2025-02-18 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('category', models.CharField(choices=[('A', 'Appetizer'), ('M', 'Main'), ('S', 'Side'), ('D', 'Dessert'), ('B', 'Beverage')], default='A', max_length=1)),
                ('claimed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('I', 'Invited'), ('A', 'Attending'), ('N', 'Not attending'), ('M', 'Maybe')], default='I', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('invite_id', models.CharField(blank=True, max_length=6, unique=True)),
                ('time', models.DateField()),
                ('location', models.CharField(max_length=150)),
                ('dresscode', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'Active'), ('C', 'Cancelled')], default='A', max_length=1)),
                ('dishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dish')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('rsvp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.rsvp')),
            ],
        ),
    ]
