# Generated by Django 5.1.6 on 2025-02-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_party_dishes_alter_party_invite_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='rsvp',
        ),
        migrations.AddField(
            model_name='party',
            name='rsvp',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.rsvp'),
        ),
    ]
