# Generated by Django 5.1.6 on 2025-02-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_party_rsvp_party_rsvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='rsvp',
            field=models.ManyToManyField(blank=True, to='main_app.rsvp'),
        ),
    ]
