# Generated by Django 5.1.6 on 2025-02-20 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_party_dishes_dish_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='rsvp',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='party',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.party'),
            preserve_default=False,
        ),
    ]
