# Generated by Django 5.1.6 on 2025-02-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_party_rsvp_rsvp_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
