# Generated by Django 5.1.6 on 2025-02-20 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_party_rsvp_rsvp_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='party',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='party',
        ),
        migrations.AddField(
            model_name='party',
            name='dishes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.dish'),
        ),
        migrations.AddField(
            model_name='party',
            name='rsvp',
            field=models.ManyToManyField(blank=True, to='main_app.rsvp'),
        ),
        migrations.AlterField(
            model_name='party',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
