# Generated by Django 5.1.6 on 2025-02-20 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_dish_party_remove_rsvp_party_party_dishes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='dishes',
        ),
        migrations.RemoveField(
            model_name='party',
            name='rsvp',
        ),
        migrations.AddField(
            model_name='dish',
            name='party',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.party'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsvp',
            name='party',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.party'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='party',
            name='time',
            field=models.DateField(),
        ),
    ]
