# Generated by Django 5.1.6 on 2025-02-20 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_party_time'),
        ('main_app', '0008_remove_party_dishes_remove_party_rsvp_dish_party_and_more'),
    ]

    operations = [
    ]
