# Generated by Django 5.1.6 on 2025-02-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_merge_20250220_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='img_url',
            field=models.URLField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
